### ISSUE TITLE
Prototype chaining iteration

### ISSUE THREAD

**Issue by Beraliv** [nanoutils/nanoutils#11]
I would recommend to use `for-in`-loop instead of implicit prototype chaining via recursion as it requires more bytes (yeah, I agree, not too much but as long as it's `nano`utils, maybe we consider this recommendation and see pros and cons of it?)

General pros:
1) lighter

General cons:
1) not functional

What do you think?

Example:

`valuesIn/index.js`
```
export default function valuesIn(obj) {
  var values = Object.keys(obj).map(function(key) {
    return obj[key]
  })
  var prototype = Object.getPrototypeOf(obj)

  return !!prototype
    ? values.concat(valuesIn(prototype))
    : values
}
```
would become:

```
export default function valuesIn(obj) {
  let values = []
  for (key in obj) {
    values.push(obj[key])
  }
  return values
}
```

For `valuesIn` it reduces size from `78B` to `47B`

We can also think of adding `_internal` method for that and call it `_prototypeCall`

**Comment by Kelin2025** [comment]
I think about it but can't imagine _internal_ methods for all cases with objects iteration (and do we really need 'em ?)

**Comment by Beraliv** [comment]
Yeah, number of methods are increasing, I think so

**Comment by Beraliv** [comment]
The project for now doesn't require prototype for-loop method therefore the issue needs to be closed
