### ISSUE TITLE
Bug: pick method doesn't include falsy properties

### ISSUE THREAD

**Issue by Kelin2025** [nanoutils/nanoutils#130]
```js
const pickState = pick(["success", "pending", "cancelled", "payload", "result"])

pickState({"cancelled": false, "payload": {"a": 1}, "pending": true, "result": null, "success": false})
```

![image](https://user-images.githubusercontent.com/4208480/44555213-c5033c00-a73c-11e8-8c9b-2885d4fc3ff2.png)

**Comment by Beraliv** [comment]
Wait for [PR #131](https://github.com/nanoutils/nanoutils/pull/131) to be merged

**Comment by Beraliv** [comment]
[PR #131](https://github.com/nanoutils/nanoutils/pull/131) is merged
