### ISSUE TITLE
Bug: over method works incorrectly

### ISSUE THREAD

**Issue by Kelin2025** [nanoutils/nanoutils#132]
Should work the same as Ramda:
```js
const abLens = lensPath(['a', 'b'])

over(abLens, item => item + 1, { a: { b: 1 } })
```

But now:
```js
over(['a', 'b'], item => item + 1, { a: { b: 1 } })
```

**Comment by Beraliv** [comment]
@Kelin2025 oh, you're right
I didn't check it yet as it starts with O :)

**Comment by Beraliv** [comment]
Updated methods, you can check changes in a commit [prod: refactor `over` and remove `updateLens`](https://github.com/nanoutils/nanoutils/commit/7cc18d737319f6c95bd3cb4714f028f9ba281cf2)
