### ISSUE TITLE
assoc works incorrectly

### ISSUE THREAD

**Issue by Kelin2025** [nanoutils/nanoutils#148]
```js
assoc('path', 1, {})
```

Throws an error because `assoc` uses `lensPath` and requires 1st arg to be an array

[`R.assoc`](https://ramdajs.com/docs/#assoc) requires a string

---

Also need to check `dissoc` method too

**Comment by Beraliv** [comment]
I didn't get it
In your case none will be thrown
Are you sure you're not talking about `assocPath`?

**Comment by Kelin2025** [comment]
Oops, I was using an old version. Mistake
