### ISSUE TITLE
Last test uses first function

### ISSUE THREAD

**Issue by sitefig** [nanoutils/nanoutils#188]
**Describe the bug**
The test for the _fast_ function, uses the _first_ function.
The test should fail.

**To Reproduce**
Open the file https://github.com/nanoutils/nanoutils/blob/master/lib/last/last.test.js
and check the test cases.

**Expected behavior**
The file last.test.js should import and reference the last function

**Examples**
https://github.com/nanoutils/nanoutils/blob/master/lib/last/last.test.js
import first from '.'

test('returns last element of array', () => {
  expect(first([1, 2, 3])).toBe(3)  /// << should be last
})

test('returns last element of string', () => {
  expect(first('hello')).toBe('o')  /// << should be last
})

**Comment by Beraliv** [comment]
It's the problem of default imports
The function itself is correct and it's renamed within `last.test.js`
You can assure yourself by checking `first.name` which returns `'last'`
