### ISSUE TITLE
Comparison with rambda?

### ISSUE THREAD

**Issue by victordidenko** [nanoutils/nanoutils#204]
Looks like [rambda](https://github.com/selfrefactor/rambda) is less sized, can you do comparison, please?
<img width="1059" alt="Screenshot 2020-01-22 at 11 45 17" src="https://user-images.githubusercontent.com/15016227/72878807-b099e900-3d0c-11ea-8a22-727ff98bad10.png">

**Comment by Beraliv** [comment]
I will have a look at it, thanks!

**Comment by Beraliv** [comment]
@victordidenko a little research in PR: https://github.com/nanoutils/nanoutils/pull/207
