### ISSUE TITLE
Arrow functions

### ISSUE THREAD

**Issue by erykpiast** [nanoutils/nanoutils#205]
I can see a possible quick win regarding bundle size optimization: arrow functions. Nanoutils don't rely on `this`, so currently used `function` syntax is kind of superfluous. Let's look at a simple example like [`trim` function](https://github.com/nanoutils/nanoutils/blob/master/lib/trim/index.js).

```javascript
function trim(str) {
  return str.trim()
}
```
vs
```javascript
(str) => str.trim()
```
After minification it's
```javascript
function t(s){return s.trim()}
```
and respectively
```javascript
(s)=>s.trim()
```
Thats `13` vs `30` characters, which is more than 50% reduction. Of course it's quite a skewed case, but you get the idea.

The only concern I can see for now is a stack trace. Instead of 
```
Uncaught TypeError: s.trim is not a function
    at t (node_modules/nanoutils/lib/trim/index.js:1:9)
    at foobar:1:16
```
we'd get a bit more vague
```
Uncaught TypeError: s.trim is not a function
    at <anonymous> (node_modules/nanoutils/lib/trim/index.js:1:9)
    at foobar:1:16
```
Personally, I don't think it's an issue (we still have a directory name and single-letter we're getting after minification is no better than `<anonymous>`), but I just want to point it here.

**Comment by Beraliv** [comment]
@erykpiast hey!

Thank you for the issue, that's a great idea

I think we need to have several bundles with different configs: i.e. old es5 syntax and es8 syntax

This is what you mean, right?

**Comment by erykpiast** [comment]
Yes, indeed, the idea requires that. I was convinced that it's already there, though. I can see [two entrypoint fields in package.json](https://github.com/nanoutils/nanoutils/blob/master/package.json#L5-L6) as well as [usage of Babel in a build script](https://github.com/nanoutils/nanoutils/blob/master/package.json#L18). Do you want to say that source files are written in ES5 syntax intentionally because there is no transpilation step making the library compatible with older browsers?

**Comment by Beraliv** [comment]
> Yes, indeed, the idea requires that. I was convinced that it's already there, though. I can see [two entrypoint fields in package.json](https://github.com/nanoutils/nanoutils/blob/master/package.json#L5-L6) as well as [usage of Babel in a build script](https://github.com/nanoutils/nanoutils/blob/master/package.json#L18). Do you want to say that source files are written in ES5 syntax intentionally because there is no transpilation step making the library compatible with older browsers?

Yeah, seems `nanoutils` has babel for simple transformations:

* transform-spread

https://github.com/nanoutils/nanoutils/blob/cf6387b1f6d8f5f6180161f2d92f1582e52c2be4/lib/composeT/index.js#L1-L3

* [transform-function-name](https://babeljs.io/docs/en/babel-plugin-transform-function-name)

(It's the case you were talking about, it can help with better debugging)

* And more cases you can see in `.babelrc`

There is no other transpilation use cases right now, but we can use several targets and remove several plugins for them so it will be frank transformation

Older browsers are supported now because of the way functions are written, yes

**Comment by erykpiast** [comment]
I like the approach with very granular transformations, it does make sense here!

I can see there is already `@babel/plugin-transform-arrow-functions` plugin in `.babelrc`, so my idea seems quite valid, doesn't it? For ESM entry point there could be arrow functions everywhere and CommonJS targets would use regular functions like it's right now. Am I missing something here?

**Comment by Beraliv** [comment]
> I like the approach with very granular transformations, it does make sense here!
> 
> I can see there is already `@babel/plugin-transform-arrow-functions` plugin in `.babelrc`, so my idea seems quite valid, doesn't it? For ESM entry point there could be arrow functions everywhere and CommonJS targets would use regular functions like it's right now. Am I missing something here?

I think you're right

**Comment by erykpiast** [comment]
Cool! I'm going to make a PR!

**Comment by Beraliv** [comment]
> Cool! I'm going to make a PR!

This would be awesome!
If you have any questions, you can write me here or in telegram
Link is in README https://github.com/nanoutils/nanoutils#nanoutils

**Comment by erykpiast** [comment]
@Beraliv, do you have any idea how can I install the app on my local machine? It seems that one dependency (`create-index`) links to a private repository, so I have no access to it.

**Comment by Beraliv** [comment]
> @Beraliv, do you have any idea how can I install the app on my local machine? It seems that one dependency (`create-index`) links to a private repository, so I have no access to it.

That's bad, I need to check it because I didn't change a code for a time

**Comment by Beraliv** [comment]
@erykpiast check out if you can install the branch from PR: https://github.com/nanoutils/nanoutils/pull/206

Do not forget to:

1. `rm -rf node_modules`
2. yarn
3. yarn size
