### ISSUE TITLE
Add size for cjs

### ISSUE THREAD

**Issue by Beraliv** [nanoutils/nanoutils#211]
⭐️ S (situation) ⭐️

`size.js` file compare nanoutils `lib` with ramda `es`

⭐️ T (task) ⭐️

Developers should understand the difference for older browsers (this is the only usage of `cjs` fmpov)

⭐️ A (action) ⭐️

Allow `size.js` accepts directory name for `nanoutils` as `ramda` uses `es` only

⭐️ R (result) ⭐️

There will be 2 files after changes: `SIZES.md` and `CJS_SIZES.md`

**Comment by erykpiast** [comment]
Do you think it's also good second issue? :)

**Comment by erykpiast** [comment]
@Beraliv do you need support with this one? I'd like to have https://github.com/nanoutils/nanoutils/pull/208 on production as soon as possible :) If you didn't start the work here yet, I can jump in, I have spare time this weekend.

**Comment by Beraliv** [comment]
> @Beraliv do you need support with this one? I'd like to have https://github.com/nanoutils/nanoutils/pull/208 on production as soon as possible :) If you didn't start the work here yet, I can jump in, I have spare time this weekend.

Yeah, that would be helpful, thanks 👍

**Comment by Beraliv** [comment]
✅ merge into master
