### ISSUE TITLE
Function "set" with "lensPath" modifies input object

### ISSUE THREAD

**Issue by adrianmroz** [nanoutils/nanoutils#219]
**Describe the bug**
`set` function modifies input object when I use lens created by `lensPath`.

**To Reproduce**
With nanoutils 0.2.0:

```
import { lensPath, set } from 'nanoutils';

const source = [{
  foo: 1,
  bar: 2
}, {
  foo: 3,
  bar: 4
}];

const lens = lensPath([0, 'foo']);
console.log('source before', source[0].foo);
const result = set(lens, 42, source);
console.log('source after', source[0].foo);
console.log('result', result[0].foo);
```

Link to code sandbox: https://codesandbox.io/s/goofy-rgb-3zyw5?file=/src/index.js

**Expected behavior**
I expect to see `source after 1` but I see `source after 42`, so `set` modified `source` object.

**Comment by Beraliv** [comment]
@adrianmroz thank you for the issue!
I will have a look and will return to you by the end of the weekend

**Comment by Beraliv** [comment]
@adrianmroz please have a look at https://github.com/nanoutils/nanoutils/pull/220
it should prevent modifying during the path
if it's working for you, I will release the changes asap

**Comment by Beraliv** [comment]
The issue was solved in https://github.com/nanoutils/nanoutils/pull/220

**Comment by adrianmroz** [comment]
I missed your PR, sorry. It works great. Many thanks!
